FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7.7-build

# RUN install_packages git

WORKDIR /usr/src/app

COPY app/* ./

RUN python -m pip install -r requirements.txt
RUN ipcluster nbextension enable

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

CMD ["jupyter-notebook", "--ip=0.0.0.0", "--port=80", "--allow-root"]
