FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7.7-build

# RUN install_packages git

WORKDIR /usr/src/app

COPY app/* ./

RUN python -m pip install -r requirements.txt

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

CMD ["jupyter-notebook"]
